spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
---

spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    url: jdbc:postgresql://10.140.0.5:5432/postgresql
#    username: postgresql
#    password: postgrespassword
#  jpa:
#    show-sql: false
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: update
  rabbitmq:
    host: 10.178.0.18
    username: guest
    password: guest
    port: 5672

  data:
    elasticsearch:
      hosts: 10.146.0.3,10.146.0.4,10.146.0.6,10.146.0.5
      port: 9200